<?php
require_once 'config.php';
$current_page = 'field_visits.php';
$page_title = 'Field Visits & Leads';
$page_subtitle = 'Manage all market leads generated by executives on the field.';
require_once 'header.php';
?>
<style>
    /* Filter Bar */
    .filter-bar {
        background: #ffffff;
        padding: 12px;
        border-radius: 12px;
        border: 1px solid #e2e8f0;
        margin-bottom: 24px;
        display: flex;
        gap: 12px;
        align-items: center;
        flex-wrap: nowrap;
        overflow-x: auto;
    }

    .search-box {
        flex: 1;
        min-width: 250px;
        position: relative;
    }
    
    .search-box i {
        position: absolute;
        left: 14px;
        top: 50%;
        transform: translateY(-50%);
        color: #94a3b8;
    }

    .search-box input {
        width: 100%;
        padding: 8px 14px 8px 40px;
        border: 1px solid #cbd5e1;
        border-radius: 20px;
        font-size: 13px;
        outline: none;
        background: #fff;
        transition: border-color 0.2s;
    }
    .search-box input:focus { border-color: #94a3b8; }
    
    .filter-select {
        padding: 8px 16px;
        border: 1px solid #e2e8f0;
        border-radius: 20px;
        font-size: 12px;
        font-weight: 600;
        background: #f8fafc;
        color: #334155;
        outline: none;
        min-width: auto;
        width: auto !important;
        flex: 0 0 auto;
        cursor: pointer;
    }

    /* Data Table */
    .table-container {
        background: #ffffff;
        border-radius: 12px;
        border: 1px solid #e2e8f0;
        overflow-x: auto;
    }

    table {
        width: 100%;
        border-collapse: collapse;
        white-space: nowrap;
    }

    th {
        background: #f8fafc;
        padding: 16px 24px;
        text-align: left;
        font-size: 10px;
        font-weight: 700;
        color: #64748b;
        text-transform: uppercase;
        letter-spacing: 0.05em;
        border-bottom: 1px solid #e2e8f0;
    }

    td {
        padding: 16px 24px;
        font-size: 14px;
        color: #0f172a;
        border-bottom: 1px solid #f1f5f9;
    }

    tr:last-child td {
        border-bottom: none;
    }
    
    tr:hover {
        background: #f8fafc;
    }
    
    .quality-badge {
        padding: 4px 10px;
        border-radius: 20px;
        font-size: 12px;
        font-weight: 600;
        display: inline-flex;
        align-items: center;
        gap: 4px;
    }
    .quality-hot { background: #fee2e2; color: #991b1b; }
    .quality-warm { background: #fef3c7; color: #92400e; }
    .quality-cold { background: #e0f2fe; color: #075985; }

    .btn-action {
        background: transparent;
        border: 1px solid #e2e8f0;
        color: #0f172a;
        padding: 6px 12px;
        border-radius: 6px;
        cursor: pointer;
        font-size: 13px;
        font-weight: 500;
        transition: 0.2s;
    }
    .btn-action:hover {
        background: #f8fafc;
    }
    
    .pagination {
        display: flex;
        justify-content: space-between;
        align-items: center;
        padding: 16px 24px;
        border-top: 1px solid #e2e8f0;
    }
    
    .page-btn {
        background: white;
        border: 1px solid #e2e8f0;
        padding: 6px 12px;
        border-radius: 6px;
        cursor: pointer;
    }
    
    .page-btn:disabled {
        opacity: 0.5;
        cursor: not-allowed;
    }

    /* Modal/Sidebar for Follow-ups */
    .modal-overlay {
        position: fixed;
        top: 0; left: 0; right: 0; bottom: 0;
        background: rgba(0,0,0,0.5);
        display: none;
        z-index: 100;
    }
    .followup-sidebar {
        position: fixed;
        top: 0; right: -450px;
        width: 450px;
        height: 100vh;
        background: white;
        box-shadow: -4px 0 15px rgba(0,0,0,0.1);
        z-index: 101;
        transition: right 0.3s ease;
        display: flex;
        flex-direction: column;
    }
    .followup-sidebar.open {
        right: 0;
    }
    .fs-header {
        padding: 24px;
        border-bottom: 1px solid #e2e8f0;
        display: flex;
        justify-content: space-between;
        align-items: center;
    }
    .fs-header h2 { font-size: 18px; margin-bottom: 4px; }
    .fs-header p { font-size: 13px; color: #64748b; }
    .fs-close { cursor: pointer; color: #64748b; font-size: 20px; }
    
    .fs-content {
        padding: 24px;
        flex: 1;
        overflow-y: auto;
    }
    
    .timeline {
        position: relative;
        margin-left: 12px;
        border-left: 2px solid #e2e8f0;
        padding-left: 20px;
        margin-bottom: 30px;
    }
    .timeline-item {
        position: relative;
        margin-bottom: 24px;
    }
    .timeline-item::before {
        content: '';
        position: absolute;
        left: -27px;
        top: 4px;
        width: 12px;
        height: 12px;
        border-radius: 50%;
        background: var(--primary, #FF7A00);
        border: 2px solid white;
    }
    .tl-date { font-size: 12px; color: #64748b; margin-bottom: 4px; }
    .tl-text { font-size: 14px; background: #F8FAFC; padding: 12px; border-radius: 8px; border: 1px solid #e2e8f0; }
    .tl-meta { font-size: 12px; font-weight: 500; margin-top: 8px; display: flex; justify-content: space-between; }
    
    .add-followup-form {
        background: #F8FAFC;
        padding: 20px;
        border-radius: 8px;
        border: 1px solid #e2e8f0;
    }
    
    .add-followup-form label {
        display: block; font-size: 13px; font-weight: 500; margin-bottom: 6px; margin-top: 12px;
    }
    .add-followup-form textarea, .add-followup-form input {
        width: 100%; padding: 10px; border: 1px solid #e2e8f0; border-radius: 6px;
    }
    
    .photo-preview {
        width: 100%;
        height: 150px;
        object-fit: cover;
        border-radius: 8px;
        margin-bottom: 16px;
        border: 1px solid #e2e8f0;
        display: none;
    }
</style>
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" />
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>
<script>
    let sidebarMap = null;
    let sidebarMarker = null;
</script>

        <!-- Filter Bar -->
        <div class="filter-bar">
            <div class="search-box">
                <i class="fas fa-search"></i>
                <input type="text" id="searchInput" placeholder="Search by Firm, Person, or Mobile..." oninput="loadData(1)">
            </div>
            <select class="filter-select" id="qualityFilter" onchange="loadData(1)">
                <option value="">All Qualities</option>
                <option value="Hot">Hot</option>
                <option value="Warm">Warm</option>
                <option value="Cold">Cold</option>
            </select>
            <select class="filter-select" id="profFilter" onchange="loadData(1)">
                <option value="">All Professions</option>
                <option value="CA">CA</option>
                <option value="PROPERTY DEALER">PROPERTY DEALER</option>
                <option value="ARCHITECT">ARCHITECT</option>
                <option value="CONTRACTOR">CONTRACTOR</option>
                <option value="BUSINESS OWNER">BUSINESS OWNER</option>
                <option value="OTHER">OTHER</option>
            </select>
            <a href="admin_tracking.php" class="btn" style="background:linear-gradient(135deg, #ff7a00, #e66a00); color:white; padding:10px 16px; border-radius:8px; text-decoration:none; font-size:14px; font-weight:600; display:flex; align-items:center; gap:8px; border:none; box-shadow:0 4px 10px rgba(255, 122, 0, 0.3); white-space:nowrap;">
                <i class="fas fa-crosshairs fa-spin-hover"></i> Live Tracking Radar
            </a>
            <a href="staff_ranking.php" class="btn" style="background:#0f172a; color:white; padding:10px 16px; border-radius:8px; text-decoration:none; font-size:14px; font-weight:600; display:flex; align-items:center; gap:8px; border:none; box-shadow:0 2px 4px rgba(0,0,0,0.15); white-space:nowrap;">
                <i class="fas fa-trophy"></i> Leaderboard
            </a>
            <a href="export_admin_visits.php" class="btn" style="background:#334155; color:white; padding:10px 16px; border-radius:8px; text-decoration:none; font-size:14px; font-weight:600; display:flex; align-items:center; gap:8px; border:none; box-shadow:0 2px 4px rgba(0,0,0,0.1); white-space:nowrap;">
                <i class="fas fa-file-excel"></i> Export All
            </a>
        </div>

        <!-- Table -->
        <div class="table-container">
            <table>
                <thead>
                    <tr>
                        <th>Date & Exec</th>
                        <th>Firm Details</th>
                        <th>Person & Contact</th>
                        <th>Profession</th>
                        <th>Lead Quality</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody id="tableBody">
                    <tr><td colspan="6" style="text-align:center;">Loading...</td></tr>
                </tbody>
            </table>
            
            <!-- Pagination -->
            <div class="pagination">
                <span id="pageInfo" style="font-size:14px;color:var(--text-muted);">Showing 1 to 10 of 0 entries</span>
                <div style="display:flex;gap:8px;">
                    <button class="page-btn" id="prevBtn" onclick="changePage(-1)">Previous</button>
                    <button class="page-btn" id="nextBtn" onclick="changePage(1)">Next</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Follow-up Sidebar/Modal -->
    <div class="modal-overlay" id="overlay" onclick="closeSidebar()"></div>
    <div class="followup-sidebar" id="sidebar">
        <div class="fs-header">
            <div>
                <h2 id="fs_firm_name">Firm Name</h2>
                <p id="fs_person_name">Person Name</p>
            </div>
            <i class="fas fa-times fs-close" onclick="closeSidebar()"></i>
        </div>
        
        <div class="fs-content">
            <div id="sidebar-map" style="height: 200px; width: 100%; border-radius: 8px; margin-bottom: 16px; border: 1px solid #cbd5e1; display: none;"></div>
            <a href="#" target="_blank" id="fs_photo_link"><img src="" class="photo-preview" id="fs_photo"></a>
            
            <div id="smart-visit-info" style="display:none; background:#f8fafc; border:1px solid #e2e8f0; border-radius:8px; padding:12px; margin-bottom:16px;"></div>
            
            <h3 style="font-size:15px;margin-bottom:16px;">Follow-up History</h3>
            <div class="timeline" id="timelineContainer">
                <!-- Timeline items injected here -->
            </div>
            
            <div class="add-followup-form">
                <h3 style="font-size:15px;margin-bottom:8px;">Add New Follow-up</h3>
                <form id="followupForm" onsubmit="submitFollowup(event)">
                    <input type="hidden" id="fv_id" name="visit_id">
                    
                    <label>Remarks</label>
                    <textarea name="remarks" rows="2" required></textarea>
                    
                    <label>Next Meeting Date</label>
                    <input type="date" name="next_meeting_date">
                    
                    <button type="submit" class="btn-primary" style="width:100%;margin-top:16px;justify-content:center;">
                        Save Follow-up
                    </button>
                </form>
            </div>
        </div>
    </div>

    <script>
        let currentPage = 1;
        let totalPages = 1;

        function initSidebarMap(lat, lng, title, subtitle) {
            const mapDiv = document.getElementById('sidebar-map');
            mapDiv.style.display = 'block';
            
            if (!sidebarMap) {
                sidebarMap = L.map('sidebar-map').setView([lat, lng], 15);
                L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
                    maxZoom: 19
                }).addTo(sidebarMap);
            } else {
                sidebarMap.setView([lat, lng], 15);
            }
            
            if (sidebarMarker) {
                sidebarMap.removeLayer(sidebarMarker);
            }
            
            sidebarMarker = L.marker([lat, lng]).addTo(sidebarMap)
                .bindPopup(`<b>${title}</b><br>${subtitle}`).openPopup();
                
            // Invalidate size after map becomes visible
            setTimeout(() => sidebarMap.invalidateSize(), 300);
        }

        function getQualityBadge(q) {
            if(!q) return '-';
            const v = q.toLowerCase();
            let icon = '';
            if(v === 'hot') icon = '';
            if(v === 'warm') icon = '️';
            if(v === 'cold') icon = '️';
            return `<span class="quality-badge quality-${v}">${icon} ${q}</span>`;
        }

        async function loadData(page = 1) {
            currentPage = page;
            const search = document.getElementById('searchInput').value;
            const quality = document.getElementById('qualityFilter').value;
            const prof = document.getElementById('profFilter').value;
            
            const tbody = document.getElementById('tableBody');
            tbody.innerHTML = '<tr><td colspan="6" style="text-align:center;">Loading data...</td></tr>';
            
            try {
                const res = await fetch(`?api=get_field_visits&page=${page}&search=${search}&quality=${quality}&prof=${prof}`);
                const data = await res.json();
                
                if (data.data.length === 0) {
                    tbody.innerHTML = '<tr><td colspan="6" style="text-align:center;">No field visits found.</td></tr>';
                    document.getElementById('pageInfo').innerText = `Showing 0 entries`;
                    return;
                }
                
                let html = '';
                data.data.forEach(row => {
                    const profDisplay = row.profession === 'OTHER' ? row.custom_profession : row.profession;
                    html += `
                        <tr>
                            <td>
                                <div style="font-weight:500;">${row.visit_date}</div>
                                <div style="font-size:12px;color:var(--text-muted);">By: ${row.executive_name}</div>
                            </td>
                            <td>
                                <div style="font-weight:500;">${row.firm_name}</div>
                                <div style="font-size:12px;color:var(--text-muted);"><i class="fas fa-map-marker-alt"></i> ${row.city}, ${row.state}</div>
                            </td>
                            <td>
                                <div>${row.person_name}</div>
                                <div style="font-size:12px;color:var(--text-muted);"><i class="fas fa-phone"></i> ${row.mobile}</div>
                            </td>
                            <td>${profDisplay}</td>
                            <td>${getQualityBadge(row.lead_quality)}</td>
                            <td>
                                <button class="btn-action" onclick="openSidebar(${row.id}, '${row.latitude}', '${row.longitude}', '${row.verified_address}')">Follow-ups / Location</button>
                            </td>
                        </tr>
                    `;
                });
                
                tbody.innerHTML = html;
                
                totalPages = data.total_pages;
                document.getElementById('pageInfo').innerText = `Page ${page} of ${totalPages} (${data.total_records} records)`;
                document.getElementById('prevBtn').disabled = page <= 1;
                document.getElementById('nextBtn').disabled = page >= totalPages;
                
            } catch (err) {
                tbody.innerHTML = '<tr><td colspan="6" style="text-align:center;color:red;">Error loading data</td></tr>';
            }
        }

        function changePage(delta) {
            const newPage = currentPage + delta;
            if (newPage >= 1 && newPage <= totalPages) {
                loadData(newPage);
            }
        }

        async function openSidebar(visitId) {
            document.getElementById('overlay').style.display = 'block';
            const sidebar = document.getElementById('sidebar');
            sidebar.classList.add('open');
            document.getElementById('fv_id').value = visitId;
            
            const timeline = document.getElementById('timelineContainer');
            timeline.innerHTML = '<p style="font-size:13px;color:#666;">Loading history...</p>';
            
            try {
                const res = await fetch(`?api=get_visit_details&id=${visitId}`);
                const data = await res.json();
                const v = data.visit;
                
                document.getElementById('fs_firm_name').innerText = v.firm_name;
                document.getElementById('fs_person_name').innerText = v.person_name + ' | ' + v.mobile;
                
                if (v.photo_path) {
                    const img = document.getElementById('fs_photo');
                    img.src = v.photo_path;
                    img.style.display = 'block';
                    document.getElementById('fs_photo_link').href = v.photo_path;
                } else {
                    document.getElementById('fs_photo').style.display = 'none';
                }
                
                // --- Live Tracking Engine ---
                document.getElementById('sidebar-map').style.display = 'none';
                try {
                    const onlineRes = await fetch('?api=get_online_staff');
                    const onlineData = await onlineRes.json();
                    
                    const staffTracking = onlineData.find(s => s.username === v.executive_name);
                    
                    if (staffTracking && staffTracking.lat) {
                        initSidebarMap(staffTracking.lat, staffTracking.lon, 
                            "Live Location (" + v.executive_name.split('@')[0] + ")", 
                            "Battery: " + (staffTracking.battery || '--') + "%<br>Status: " + staffTracking.status);
                    } else if (v.latitude && v.longitude) {
                        // Fallback to capture location if offline
                        initSidebarMap(v.latitude, v.longitude, 
                            "Location at Capture", 
                            "Staff is currently offline.<br>This is where the lead was generated.");
                    }
                } catch(e) { console.log('Map Error:', e); }
                // --- End Live Tracking ---
                
                // --- Smart Visit Info ---
                const smartBlock = document.getElementById('smart-visit-info');
                let smartHtml = '<h4 style="font-size:13px; font-weight:600; color:#334155; margin-bottom:8px; display:flex; justify-content:space-between;"><span><i class="fas fa-microchip" style="color:#3b82f6;"></i> Smart Check-in Data</span></h4>';
                
                let hasSmartData = false;
                
                if (v.check_in_time) {
                    hasSmartData = true;
                    smartHtml += `<div style="font-size:12px; color:#475569; margin-bottom:4px;"><b>Check-in:</b> ${v.check_in_time}</div>`;
                }
                if (v.check_out_time) {
                    hasSmartData = true;
                    smartHtml += `<div style="font-size:12px; color:#475569; margin-bottom:4px;"><b>Check-out:</b> ${v.check_out_time}</div>`;
                }
                if (v.verified_address) {
                    hasSmartData = true;
                    smartHtml += `<div style="font-size:12px; color:#475569; margin-bottom:4px;"><b>GPS Address:</b> ${v.verified_address}</div>`;
                }
                if (v.audio_path) {
                    hasSmartData = true;
                    smartHtml += `<div style="margin-top:8px; font-size:12px; font-weight:600; color:#334155;">Voice Recording:</div>
                                  <audio controls style="width:100%; height:32px; margin-top:4px; outline:none;">
                                      <source src="${v.audio_path}" type="audio/webm">
                                      Your browser does not support the audio element.
                                  </audio>`;
                }
                
                if (v.remarks && v.remarks.includes('GPS Distance Alert')) {
                    hasSmartData = true;
                    smartHtml += `<div style="margin-top:8px; background:#fee2e2; color:#991b1b; padding:8px; border-radius:6px; font-size:11.5px; border:1px solid #fca5a5;"><i class="fas fa-exclamation-triangle"></i> <b>System Alert:</b> Distance Check Failed at Check-out.</div>`;
                }
                
                if (hasSmartData) {
                    smartBlock.innerHTML = smartHtml;
                    smartBlock.style.display = 'block';
                } else {
                    smartBlock.style.display = 'none';
                }
                
                // Manually trigger map size recalculation
                setTimeout(() => { if (sidebarMap) sidebarMap.invalidateSize(); }, 300);

                let tlHtml = '';
                // Add the initial visit as the first timeline item
                tlHtml += `
                    <div class="timeline-item">
                        <div class="tl-date">${v.visit_date} - Initial Visit</div>
                        <div class="tl-text">Added as a new lead. Quality: ${v.lead_quality || 'N/A'}</div>
                        <div class="tl-meta"><span>By: ${v.executive_name}</span></div>
                    </div>
                `;
                
                data.followups.forEach(f => {
                    tlHtml += `
                        <div class="timeline-item">
                            <div class="tl-date">${f.created_at}</div>
                            <div class="tl-text">${f.remarks}</div>
                            <div class="tl-meta">
                                <span>By: ${f.added_by}</span>
                                <span style="color:var(--primary);"><i class="fas fa-calendar"></i> Next: ${f.next_meeting_date || 'N/A'}</span>
                            </div>
                        </div>
                    `;
                });
                
                timeline.innerHTML = tlHtml;
                
            } catch (err) {
                timeline.innerHTML = '<p style="color:red;">Error loading details</p>';
            }
        }

        function closeSidebar() {
            document.getElementById('overlay').style.display = 'none';
            document.getElementById('sidebar').classList.remove('open');
        }

        async function submitFollowup(e) {
            e.preventDefault();
            const form = document.getElementById('followupForm');
            const formData = new FormData(form);
            
            try {
                const res = await fetch('?api=add_visit_followup', {
                    method: 'POST',
                    body: formData
                });
                if (res.ok) {
                    form.reset();
                    const visitId = document.getElementById('fv_id').value;
                    openSidebar(visitId); // Reload timeline
                } else {
                    alert('Error saving follow-up');
                }
            } catch (err) {
                alert('Network Error');
            }
        }

        // Init
        loadData(1);
    </script>
<?php require_once 'footer.php'; ?>
