import os

# 1. Update staff/index.php to point to ../api.php
idx_path = r'c:\Users\pc\Downloads\client mgmt2\staff\index.php'
with open(idx_path, 'r', encoding='utf-8') as f:
    idx = f.read()

idx = idx.replace('fetch(`?api=get_staff_performance', 'fetch(`../api.php?api=get_staff_performance')
idx = idx.replace('fetch(`?api=get_staff_recent_leads', 'fetch(`../api.php?api=get_staff_recent_leads')

with open(idx_path, 'w', encoding='utf-8') as f:
    f.write(idx)


# 2. Add the missing APIs to api.php
api_path = r'c:\Users\pc\Downloads\client mgmt2\api.php'
with open(api_path, 'r', encoding='utf-8') as f:
    api = f.read()

new_apis = """
        case 'get_staff_performance':
            if (!isset($_SESSION['user_id'])) { echo json_encode(['error' => 'Unauthorized']); exit; }
            $u = $_GET['username'] ?? $_SESSION['username'];
            
            // Total visits
            $v_stmt = $db->prepare("SELECT COUNT(*) FROM field_visits WHERE executive_name = ?");
            $v_stmt->execute([$u]);
            $tv = $v_stmt->fetchColumn();
            
            // Total leads (applicants generated by this user)
            $l_stmt = $db->prepare("SELECT COUNT(*) FROM applicants WHERE added_by = ?");
            $l_stmt->execute([$u]);
            $tl = $l_stmt->fetchColumn();
            
            echo json_encode([
                'total_visits' => $tv,
                'total_leads' => $tl,
                'total_commission' => 0 // Can be expanded later
            ]);
            break;

        case 'get_staff_recent_leads':
            if (!isset($_SESSION['user_id'])) { echo json_encode(['error' => 'Unauthorized']); exit; }
            $u = $_GET['username'] ?? $_SESSION['username'];
            
            $stmt = $db->prepare("SELECT id, customer_name, loan_type, loan_amount_requested, created_at, overall_status FROM applicants WHERE added_by = ? ORDER BY created_at DESC LIMIT 5");
            $stmt->execute([$u]);
            echo json_encode($stmt->fetchAll(PDO::FETCH_ASSOC));
            break;
"""

if "case 'get_staff_performance':" not in api:
    api = api.replace('default:', new_apis + '\n        default:')
    with open(api_path, 'w', encoding='utf-8') as f:
        f.write(api)

print("Dashboard fixed!")
