import os
import re

api_path = r'c:\Users\pc\Downloads\client mgmt2\api.php'
with open(api_path, 'r', encoding='utf-8') as f:
    api = f.read()

target = """            // Total leads (applicants generated by this user)
            $l_stmt = $db->prepare("SELECT COUNT(*) FROM applicants WHERE added_by = ?");
            $l_stmt->execute([$u]);
            $tl = $l_stmt->fetchColumn();
            
            echo json_encode([
                'total_visits' => $tv,
                'total_leads' => $tl,
                'total_commission' => 0 // Can be expanded later
            ]);"""

repl = """            // Total leads (applicants generated by this user)
            $l_stmt = $db->prepare("SELECT COUNT(*) FROM applicants WHERE added_by = ?");
            $l_stmt->execute([$u]);
            $tl = $l_stmt->fetchColumn();
            
            // Get Employee Commission Rate
            $uid = $_SESSION['user_id'];
            $c_stmt = $db->prepare("SELECT commission_rate FROM employees WHERE user_id = ?");
            $c_stmt->execute([$uid]);
            $crate = $c_stmt->fetchColumn();
            $crate = $crate ? $crate : 0;
            
            // Get Total Commission Earned from payout_distributions
            $p_stmt = $db->prepare("SELECT SUM(net_payable) FROM payout_distributions WHERE payee_type = 'Staff' AND payee_user_id = ?");
            $p_stmt->execute([$uid]);
            $t_comm = $p_stmt->fetchColumn();
            $t_comm = $t_comm ? $t_comm : 0;
            
            echo json_encode([
                'total_visits' => $tv,
                'total_leads' => $tl,
                'total_commission' => $t_comm,
                'commission_rate' => $crate
            ]);"""

api = api.replace(target, repl)

with open(api_path, 'w', encoding='utf-8') as f:
    f.write(api)
print("api.php updated for commission rate")
